# This file created by conda-build 2.1.18
# meta.yaml template originally from:
# /Users/distiller/project/recipes/blat, last modified Thu May 10 15:13:59 2018
# ------------------------------------------------

package:
    name: blat
    version: '36'
source:
    fn: blatSrc36.zip
    sha256: 4b0fff006c86dceb7428922bfb4f8625d78fd362d205df68e4ebba04742d2c71
    url: http://hgwdev.cse.ucsc.edu/~kent/src/blatSrc36.zip
build:
    noarch: ''
    noarch_python: false
    number: '0'
    string: '0'
requirements:
    build:
        - libpng 1.6.34 0
        - zlib 1.2.11 0
    run:
        - libpng
        - zlib 1.2.11*
test:
    commands:
        - blat | grep -q "^blat - Standalone BLAT"
about:
    home: https://genome.ucsc.edu/FAQ/FAQblat.html
    license: Free for academic, nonprofit and personal use
    summary: BLAT is a bioinformatics software tool which performs rapid mRNA/DNA
        and cross-species protein alignments.
extra:
    final: true
    identifiers:
        - biotools:blat
